### ISSUE TITLE
Document how to use tasty-discover with tasty-rerun ingredient

### ISSUE THREAD

**Issue by mystilleef** [ocharles/tasty-rerun#19]
I've been looking all over the place for how to use the tasty-rerun ingredient with tasty-discover. 

I've tried the following, but that's obviously wrong.

{-# OPTIONS_GHC -F -pgmF tasty-discover -optF --ingredient=Test.Tasty.Ingredients.Rerun.rerunningTests #-}

I've also tried adding the --rerurn option to the pragma but that doesn't work either.

Maybe the answer is obvious to experienced Haskell users. But for new users, like myself, the exact Pragma to get it running without much fuss will be appreciated.

**Comment by Bodigrim** [comment]
Good question!

The problem is that `tasty-rerun` is not an ingredient, but an ingredient transformer. `tasty-discover` invariably [generates](https://git.coop/decentral1se/tasty-discover/-/blob/master/library/Test/Tasty/Discover.hs#L64) `T.defaultMainWithIngredients ingredients`, while to invoke `tasty-rerun` one has to write `T.defaultMainWithIngredients [rerunningTests ingredients]`.

Unfortunately, there is nothing we can do on the side of `tasty-rerun`: when you run `tasty-discover`, it is fully in control of code generation and cannot be affected by `tasty-rerun`. Could `tasty-discovery` possibly have a command-line flag to apply `rerunningTests` transformation? @mystilleef could you please raise this issue at https://git.coop/decentral1se/tasty-discover/-/issues?

**Comment by mystilleef** [comment]
Okay, I will.
